apiVersion: v2
name: alertmanager
description: Prometheus AlertManager — standalone alert routing
version: 1.0.0
dependencies:
  - name: alertmanager
    version: "1.38.1"
    repository: "file://../reference-charts/alertmanager"
