{{- if .Values.apps.alertmanager }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "9"
spec:
  project: hub
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: alertmanager
    helm:
      releaseName: alertmanager
  destination:
    server: {{ .Values.clusterURL }}
    namespace: monitoring
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /status
        - /metadata/finalizers
        - /spec/data
    - group: external-secrets.io
      kind: ExternalSecret
      managedFieldsManagers:
        - external-secrets
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/volumeClaimTemplates/0/status
    - group: apps
      kind: StatefulSet
      managedFieldsManagers:
        - kube-controller-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}
