{{- if .Values.apps.argocdProjects }}
{{- include "app.standard" (dict
    "name"           "argocd-projects"
    "wave"           "1"
    "path"           "argocd/projects"
    "namespace"      "argocd"
    "repoURL"        .Values.repoURL
    "targetRevision" .Values.targetRevision
    "clusterURL"     .Values.clusterURL
) }}
{{- end }}
