{{- if .Values.apps.certManager }}
{{- include "app.standard" (dict
    "name"           "cert-manager"
    "wave"           "3"
    "path"           "cert-manager"
    "namespace"      "cert-manager"
    "repoURL"        .Values.repoURL
    "targetRevision" .Values.targetRevision
    "clusterURL"     .Values.clusterURL
) }}
{{- end }}
