{{- if .Values.apps.externalSecrets }}
{{- include "app.standard" (dict
    "name"           "external-secrets"
    "wave"           "6"
    "path"           "external-secrets"
    "namespace"      "external-secrets"
    "repoURL"        .Values.repoURL
    "targetRevision" .Values.targetRevision
    "clusterURL"     .Values.clusterURL
) }}
{{- end }}
