{{- if .Values.apps.grafana }}
{{- include "app.standard" (dict
    "name"           "grafana"
    "wave"           "9"
    "path"           "grafana"
    "namespace"      "monitoring"
    "repoURL"        .Values.repoURL
    "targetRevision" .Values.targetRevision
    "clusterURL"     .Values.clusterURL
) }}
{{- end }}
