{{- if .Values.apps.longhorn }}
{{- include "app.standard" (dict
    "name"           "longhorn"
    "wave"           "4"
    "path"           "longhorn"
    "namespace"      "longhorn-system"
    "repoURL"        .Values.repoURL
    "targetRevision" .Values.targetRevision
    "clusterURL"     .Values.clusterURL
) }}
{{- end }}
