{{- if .Values.apps.mimir }}
{{- include "app.standard" (dict
    "name"           "mimir"
    "wave"           "7"
    "path"           "mimir"
    "namespace"      "monitoring"
    "repoURL"        .Values.repoURL
    "targetRevision" .Values.targetRevision
    "clusterURL"     .Values.clusterURL
) }}
{{- end }}
