{{- if .Values.apps.tempo }}
{{- include "app.standard" (dict
    "name"           "tempo"
    "wave"           "8"
    "path"           "tempo"
    "namespace"      "monitoring"
    "repoURL"        .Values.repoURL
    "targetRevision" .Values.targetRevision
    "clusterURL"     .Values.clusterURL
) }}
{{- end }}
