{{- if .Values.apps.trustManager }}
{{- include "app.standard" (dict
    "name"           "trust-manager"
    "wave"           "4"
    "path"           "trust-manager"
    "namespace"      "cert-manager"
    "repoURL"        .Values.repoURL
    "targetRevision" .Values.targetRevision
    "clusterURL"     .Values.clusterURL
) }}
{{- end }}
