{{- if .Values.apps.vault }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: hub
  source:
    repoURL: {{ .Values.repoURL }}
    targetRevision: {{ .Values.targetRevision }}
    path: vault
    helm:
      releaseName: vault
  destination:
    server: {{ .Values.clusterURL }}
    namespace: vault
  ignoreDifferences:
    - group: external-secrets.io
      kind: ExternalSecret
      jsonPointers:
        - /status
        - /metadata/finalizers
        - /spec/data
    - group: external-secrets.io
      kind: ExternalSecret
      managedFieldsManagers:
        - external-secrets
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/updateStrategy
        - /spec/persistentVolumeClaimRetentionPolicy
        - /spec/volumeClaimTemplates
      managedFieldsManagers:
        - kube-controller-manager
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - kind: Secret
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
{{- end }}
