repoURL: https://github.com/yasin-2000-cyber/infra-charts.git
targetRevision: spine-gitops
clusterURL: https://100.64.5.61:6443
domain: spine01.caticloud.net

apps:
  metallb: true
  ingressNginx: true
  certManager: true
  alloy: true
  kubeStateMetrics: true
  nodeExporter: true
  otelOperator: true
