apiVersion: v2
name: external-secrets
description: External Secrets Operator — syncs secrets from Vault into K8s Secrets
version: 1.0.0
dependencies:
  - name: external-secrets
    version: "0.10.7"
    repository: "https://charts.external-secrets.io"
