{{- if .Values.apps.kubeStateMetrics }}
{{- include "spine.app" (dict
    "name"            "kube-state-metrics"
    "wave"            "4"
    "path"            "spokes/spine-test/kube-state-metrics"
    "namespace"       "monitoring"
    "repoURL"         .Values.repoURL
    "targetRevision"  .Values.targetRevision
    "clusterURL"      .Values.clusterURL
) }}
{{- end }}
