apiVersion: v2
name: trust-manager
description: trust-manager — distributes the internal CA bundle to all namespaces that need it
version: 1.0.0
dependencies:
  - name: trust-manager
    version: "v0.22.1"
    repository: "https://charts.jetstack.io"
