apiVersion: v2
name: cert-manager
description: cert-manager — TLS certificate automation
version: 1.0.0
dependencies:
  - name: cert-manager
    version: "v1.20.2"
    repository: "file://../reference-charts/cert-manager"
