opentelemetry-operator:
  # cert-manager handles the webhook TLS certificates
  admissionWebhooks:
    certManager:
      enabled: true

  manager:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi

